# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The Foundry Visionmongers Ltd

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # See docs, they say not to use '.github'
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[CI]"
    ignore:
      # TODO(DF): Remove once no longer stuck on ASWF CY22 Docker image
      # for CI (causing nodejs glibc error).
      - dependency-name: "actions/checkout"
        update-types: [ "version-update:semver-major" ]
