# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The Foundry Visionmongers Ltd
#
name: Code quality
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pylint:
    runs-on: ubuntu-22.04
    name: Pylint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download wheels from OpenAssetIO main
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheels.yml
          workflow_conclusion: success
          name: openassetio-wheels
          repo: OpenAssetIO/OpenAssetIO
          path: deps

      - name: Install dependencies
        run: |
          python -m pip install --find-links ./deps openassetio
          python -m pip install -r requirements.txt
          python -m pip install -r tests/requirements.txt

      - name: Lint
        uses: TheFoundryVisionmongers/fn-pylint-action@v2.0
        with:
          pylint-args: >
            --disable=fixme
            --rcfile=./pyproject.toml
            python
            tests

  black:
    runs-on: ubuntu-22.04
    name: Python formatting
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install black

      - name: Check Python formatting
        run: black --diff --check .

  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

