# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 The Foundry Visionmongers Ltd
#
name: Code quality
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pylint:
    runs-on: ubuntu-22.04
    name: Pylint
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        # Pin openassetio to match C++ version, since
        # tests/requirements.txt specifies a range. Also see
        # build_openassetio action.
        run: |
          python -m pip install openassetio==1.0.0rc1.rev0
          python -m pip install -r requirements.txt
          python -m pip install -r tests/requirements.txt

      - name: Lint
        uses: TheFoundryVisionmongers/fn-pylint-action@v2.0
        with:
          pylint-args: >
            --disable=fixme
            --rcfile=./pyproject.toml
            python
            tests

  black:
    runs-on: ubuntu-22.04
    name: Python formatting
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install black

      - name: Check Python formatting
        run: black --diff --check .

  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: gaurav-nelson/github-action-markdown-link-check@v1

